"""
Dynamic Closure Notebook — Entry 06
Why a Cyclic Dynamic Closure Requires Phase and Shift Generators

Scientific purpose
------------------
Entry 05 established:

    cyclic phase Z + cyclic shift X + unital associative composition
        -> M_k(C)
        -> dimension k^2.

Entry 06 addresses the preceding EDF-specific bridge.

The derivation begins from two distinct requirements of a dynamic cyclic kernel:

A. Phase distinguishability:
   the k closure sectors carry the roots-of-unity phase labels

       A_k = {exp(2*pi*i*m/k) : m in Z_k}.

   In the sector basis |m>, this gives the phase operator

       Z|m> = omega^m |m>.

B. Cyclic traversal:
   a genuinely dynamic cycle must permit progression from one sector to its
   cyclic successor. The homogeneous successor map is

       X|m> = |m+1 mod k>.

More generally, any phase-dressed homogeneous traversal

       T|m> = exp(i*theta_m)|m+1>

with exact cycle closure T^k = I is gauge-equivalent to X by a diagonal
rephasing of the basis.

Therefore, if EDF requires both phase-resolved sectors and actual cyclic
traversal, then the phase and shift generators are not imported externally:
they are the canonical operators representing those two requirements.

Key algebraic diagnostics
-------------------------
1. Algebra generated by Z alone:
       span{I, Z, ..., Z^(k-1)}
   has dimension k and is commutative.

2. Algebra generated by X alone:
       span{I, X, ..., X^(k-1)}
   has dimension k and is commutative.

3. Algebra generated by X and Z:
       span{X^a Z^b : a,b in Z_k}
   has dimension k^2 and equals M_k(C).

4. Phase-only evolution cannot move occupation between sector basis states.
   It changes phases but leaves |psi_m|^2 invariant.

5. Shift-only evolution moves occupation cyclically but contains no
   sector-diagonal phase labeling in the original sector basis.

6. The discrete Fourier transform exchanges the phase and shift descriptions:

       F^dagger Z F = X
       F^dagger X F = Z^(-1)

   for the Fourier convention used here.

Gauge-equivalence theorem for traversal
---------------------------------------
Let

    T|m> = exp(i*theta_m)|m+1 mod k>

and assume exact cycle closure

    T^k = I.

Then

    sum_m theta_m = 0 mod 2*pi.

Define a diagonal unitary gauge

    G = diag(exp(i*alpha_m))

with

    alpha_0 = 0,
    alpha_(m+1) = alpha_m + theta_m.

The cycle-closure condition makes this definition consistent around the ring,
and

    G^dagger T G = X.

Since G is diagonal, it commutes with Z, so the phase operator is unchanged by
this gauge choice.

Thus a phase-dressed cyclic successor is structurally equivalent to the
canonical shift.

Status
------
This notebook proves a conditional structural statement:

    IF the EDF phase kernel A_k is physically resolved by phase labels,
    AND the closure process genuinely traverses the cyclic sectors,
    AND a completed cycle returns to the same physical state,
    THEN the canonical finite-dimensional representation contains both
    Z and X (up to gauge), hence the Weyl pair is internally motivated.

The remaining physical question is whether those premises are indeed part of
the foundational EDF dynamics. The notebook does not assume that conclusion
silently.

All code, labels, comments, tables, and figures are in English.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


@dataclass
class Config:
    k_min: int = 2
    k_max: int = 24

    gauge_trials_per_k: int = 100
    random_seed: int = 112358

    output_dir: str = "dynamic_closure_entry_06_output"


def clock_and_shift(k: int) -> tuple[complex, np.ndarray, np.ndarray]:
    """Return omega, X, Z for the canonical cyclic sector basis."""
    omega = np.exp(2j * np.pi / k)

    x = np.zeros((k, k), dtype=complex)
    for m in range(k):
        x[(m + 1) % k, m] = 1.0

    z = np.diag(
        np.array([omega**m for m in range(k)], dtype=complex)
    )

    return omega, x, z


def discrete_fourier(k: int) -> np.ndarray:
    """
    Fourier convention:
        F[m,n] = omega^(m*n) / sqrt(k)

    With this convention:
        F^dagger Z F = X
        F^dagger X F = Z^(-1)
    """
    omega = np.exp(2j * np.pi / k)

    return np.array(
        [
            [omega ** (m * n) / np.sqrt(k) for n in range(k)]
            for m in range(k)
        ],
        dtype=complex,
    )


def matrix_span_rank(matrices: list[np.ndarray]) -> int:
    """Return the numerical rank of the vectorized matrix family."""
    flattened = np.column_stack(
        [matrix.reshape(-1) for matrix in matrices]
    )
    return int(np.linalg.matrix_rank(flattened))


def single_generator_algebra_dimension(
    generator: np.ndarray,
    k: int,
) -> int:
    """
    Dimension of span{I, G, ..., G^(k-1)}.
    """
    matrices = [
        np.linalg.matrix_power(generator, power)
        for power in range(k)
    ]
    return matrix_span_rank(matrices)


def pair_generator_algebra_dimension(
    x: np.ndarray,
    z: np.ndarray,
    k: int,
) -> int:
    """
    Dimension of span{X^a Z^b : a,b in Z_k}.
    """
    matrices = []

    for a in range(k):
        xa = np.linalg.matrix_power(x, a)

        for b in range(k):
            zb = np.linalg.matrix_power(z, b)
            matrices.append(xa @ zb)

    return matrix_span_rank(matrices)


def random_closed_traversal(
    k: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Construct

        T|m> = exp(i theta_m)|m+1>

    with exact cycle closure T^k = I.

    Random theta_0,...,theta_(k-2) are drawn uniformly. The final angle is
    chosen so that the total phase around the cycle is exactly zero modulo
    2*pi.
    """
    theta = np.empty(k, dtype=float)

    if k > 1:
        theta[:-1] = rng.uniform(-np.pi, np.pi, size=k - 1)
        theta[-1] = -np.sum(theta[:-1])
    else:
        theta[0] = 0.0

    t = np.zeros((k, k), dtype=complex)

    for m in range(k):
        t[(m + 1) % k, m] = np.exp(1j * theta[m])

    return theta, t


def gauge_from_traversal_phases(theta: np.ndarray) -> np.ndarray:
    """
    Construct G = diag(exp(i alpha_m)) with
        alpha_0 = 0,
        alpha_(m+1) = alpha_m + theta_m.

    The final consistency condition follows from sum(theta)=0 mod 2*pi.
    """
    k = len(theta)
    alpha = np.zeros(k, dtype=float)

    for m in range(k - 1):
        alpha[m + 1] = alpha[m] + theta[m]

    return np.diag(np.exp(1j * alpha))


def verify_gauge_equivalence(
    k: int,
    rng: np.random.Generator,
) -> dict:
    """
    Verify:
        T^k = I
        G^dagger T G = X
        [G,Z] = 0
        ZT = omega TZ
    """
    omega, x, z = clock_and_shift(k)
    theta, t = random_closed_traversal(k, rng)
    g = gauge_from_traversal_phases(theta)

    identity = np.eye(k, dtype=complex)

    cycle_error = np.linalg.norm(
        np.linalg.matrix_power(t, k) - identity,
        ord="fro",
    )

    gauge_error = np.linalg.norm(
        g.conj().T @ t @ g - x,
        ord="fro",
    )

    gauge_phase_commutator_error = np.linalg.norm(
        g @ z - z @ g,
        ord="fro",
    )

    dressed_weyl_error = np.linalg.norm(
        z @ t - omega * t @ z,
        ord="fro",
    )

    return {
        "k": k,
        "cycle_closure_error": float(cycle_error),
        "gauge_to_shift_error": float(gauge_error),
        "gauge_phase_commutator_error": float(
            gauge_phase_commutator_error
        ),
        "dressed_weyl_relation_error": float(dressed_weyl_error),
        "total_traversal_phase": float(np.sum(theta)),
    }


def verify_fourier_duality(k: int) -> dict:
    """Verify the DFT exchange between Z and X."""
    _, x, z = clock_and_shift(k)
    f = discrete_fourier(k)

    identity = np.eye(k, dtype=complex)

    unitarity_error = np.linalg.norm(
        f.conj().T @ f - identity,
        ord="fro",
    )

    phase_to_shift_error = np.linalg.norm(
        f.conj().T @ z @ f - x,
        ord="fro",
    )

    shift_to_phase_error = np.linalg.norm(
        f.conj().T @ x @ f - z.conj().T,
        ord="fro",
    )

    return {
        "k": k,
        "fourier_unitarity_error": float(unitarity_error),
        "Fdag_Z_F_minus_X_error": float(phase_to_shift_error),
        "Fdag_X_F_minus_Zinv_error": float(shift_to_phase_error),
    }


def verify_phase_only_occupation_invariance(
    k: int,
    rng: np.random.Generator,
) -> dict:
    """
    Apply a random power Z^r to a random normalized state and verify that
    sector occupations |psi_m|^2 remain unchanged.
    """
    _, x, z = clock_and_shift(k)

    psi = (
        rng.normal(size=k)
        + 1j * rng.normal(size=k)
    )
    psi /= np.linalg.norm(psi)

    power = int(rng.integers(0, k))

    phase_evolved = np.linalg.matrix_power(z, power) @ psi
    shift_evolved = x @ psi

    initial_occupation = np.abs(psi) ** 2
    phase_occupation = np.abs(phase_evolved) ** 2
    shift_occupation = np.abs(shift_evolved) ** 2

    phase_occupation_change = np.linalg.norm(
        phase_occupation - initial_occupation,
        ord=1,
    )

    shift_expected = np.roll(initial_occupation, 1)

    shift_permutation_error = np.linalg.norm(
        shift_occupation - shift_expected,
        ord=1,
    )

    return {
        "k": k,
        "phase_power": power,
        "phase_only_occupation_change_L1": float(
            phase_occupation_change
        ),
        "shift_permutation_error_L1": float(
            shift_permutation_error
        ),
    }


def algebra_dimension_table(config: Config) -> pd.DataFrame:
    rows = []

    for k in range(config.k_min, config.k_max + 1):
        _, x, z = clock_and_shift(k)

        dim_z = single_generator_algebra_dimension(z, k)
        dim_x = single_generator_algebra_dimension(x, k)
        dim_xz = pair_generator_algebra_dimension(x, z, k)

        rows.append(
            {
                "k": k,
                "phase_only_dimension": dim_z,
                "shift_only_dimension": dim_x,
                "phase_shift_dimension": dim_xz,
                "expected_single_generator_dimension": k,
                "expected_pair_dimension": k * k,
            }
        )

    return pd.DataFrame(rows)


def gauge_diagnostics_table(config: Config) -> pd.DataFrame:
    master_rng = np.random.default_rng(config.random_seed)
    rows = []

    for k in range(config.k_min, config.k_max + 1):
        for trial in range(config.gauge_trials_per_k):
            seed = int(master_rng.integers(0, 2**32 - 1))
            rng = np.random.default_rng(seed)

            result = verify_gauge_equivalence(k, rng)
            result["trial"] = trial
            result["seed"] = seed
            rows.append(result)

    return pd.DataFrame(rows)


def phase_dynamics_table(config: Config) -> pd.DataFrame:
    master_rng = np.random.default_rng(config.random_seed + 1_000_003)
    rows = []

    for k in range(config.k_min, config.k_max + 1):
        seed = int(master_rng.integers(0, 2**32 - 1))
        rng = np.random.default_rng(seed)

        result = verify_phase_only_occupation_invariance(k, rng)
        result["seed"] = seed
        rows.append(result)

    return pd.DataFrame(rows)


def plot_algebra_dimensions(
    table: pd.DataFrame,
    output_dir: Path,
) -> None:
    plt.figure(figsize=(9, 5))

    plt.plot(
        table["k"],
        table["phase_only_dimension"],
        marker="o",
        label="Phase generator only",
    )

    plt.plot(
        table["k"],
        table["shift_only_dimension"],
        marker="x",
        label="Shift generator only",
    )

    plt.plot(
        table["k"],
        table["phase_shift_dimension"],
        marker="o",
        label="Phase + shift generators",
    )

    plt.xlabel("Closure sector count k")
    plt.ylabel("Generated algebra dimension")
    plt.title("Generator Sufficiency: k versus k^2")
    plt.legend(frameon=False)
    plt.tight_layout()
    plt.savefig(
        output_dir / "generator_algebra_dimensions.png",
        dpi=180,
    )
    plt.close()


def plot_dimension_ratio(
    table: pd.DataFrame,
    output_dir: Path,
) -> None:
    plt.figure(figsize=(9, 5))

    plt.plot(
        table["k"],
        table["phase_only_dimension"] / (table["k"] ** 2),
        marker="o",
        label="Phase only / full operator dimension",
    )

    plt.plot(
        table["k"],
        table["shift_only_dimension"] / (table["k"] ** 2),
        marker="x",
        label="Shift only / full operator dimension",
    )

    plt.plot(
        table["k"],
        table["phase_shift_dimension"] / (table["k"] ** 2),
        marker="o",
        label="Phase + shift / full operator dimension",
    )

    plt.xlabel("Closure sector count k")
    plt.ylabel("Fraction of full operator space")
    plt.title("Fraction of M_k(C) Generated by the Available Operators")
    plt.legend(frameon=False)
    plt.tight_layout()
    plt.savefig(
        output_dir / "generated_operator_fraction.png",
        dpi=180,
    )
    plt.close()


def plot_gauge_errors(
    gauge_summary: pd.DataFrame,
    output_dir: Path,
) -> None:
    plt.figure(figsize=(9, 5))

    plt.semilogy(
        gauge_summary["k"],
        gauge_summary["max_cycle_closure_error"] + 1e-18,
        marker="o",
        label="Cycle closure error",
    )

    plt.semilogy(
        gauge_summary["k"],
        gauge_summary["max_gauge_to_shift_error"] + 1e-18,
        marker="o",
        label="Gauge-to-shift error",
    )

    plt.semilogy(
        gauge_summary["k"],
        gauge_summary["max_dressed_weyl_relation_error"] + 1e-18,
        marker="o",
        label="Dressed Weyl relation error",
    )

    plt.xlabel("Closure sector count k")
    plt.ylabel("Maximum numerical error")
    plt.title("Gauge Equivalence of Closed Cyclic Traversal")
    plt.legend(frameon=False)
    plt.tight_layout()
    plt.savefig(
        output_dir / "gauge_equivalence_errors.png",
        dpi=180,
    )
    plt.close()


def plot_phase_occupation_invariance(
    phase_dynamics: pd.DataFrame,
    output_dir: Path,
) -> None:
    plt.figure(figsize=(9, 5))

    plt.semilogy(
        phase_dynamics["k"],
        phase_dynamics["phase_only_occupation_change_L1"] + 1e-18,
        marker="o",
        label="Occupation change under phase-only action",
    )

    plt.semilogy(
        phase_dynamics["k"],
        phase_dynamics["shift_permutation_error_L1"] + 1e-18,
        marker="x",
        label="Shift permutation error",
    )

    plt.xlabel("Closure sector count k")
    plt.ylabel("L1 error / change")
    plt.title("Phase Labeling Does Not Produce Sector Traversal")
    plt.legend(frameon=False)
    plt.tight_layout()
    plt.savefig(
        output_dir / "phase_only_occupation_invariance.png",
        dpi=180,
    )
    plt.close()


def main() -> None:
    config = Config()
    output_dir = Path(config.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    dimensions = algebra_dimension_table(config)
    dimensions.to_csv(
        output_dir / "generator_algebra_dimensions.csv",
        index=False,
    )

    fourier = pd.DataFrame(
        [
            verify_fourier_duality(k)
            for k in range(config.k_min, config.k_max + 1)
        ]
    )
    fourier.to_csv(
        output_dir / "fourier_duality_diagnostics.csv",
        index=False,
    )

    gauge = gauge_diagnostics_table(config)
    gauge.to_csv(
        output_dir / "gauge_equivalence_trials.csv",
        index=False,
    )

    gauge_summary = (
        gauge.groupby("k", as_index=False)
        .agg(
            max_cycle_closure_error=("cycle_closure_error", "max"),
            max_gauge_to_shift_error=("gauge_to_shift_error", "max"),
            max_gauge_phase_commutator_error=(
                "gauge_phase_commutator_error",
                "max",
            ),
            max_dressed_weyl_relation_error=(
                "dressed_weyl_relation_error",
                "max",
            ),
        )
    )
    gauge_summary.to_csv(
        output_dir / "gauge_equivalence_summary.csv",
        index=False,
    )

    phase_dynamics = phase_dynamics_table(config)
    phase_dynamics.to_csv(
        output_dir / "phase_only_dynamics_diagnostics.csv",
        index=False,
    )

    plot_algebra_dimensions(dimensions, output_dir)
    plot_dimension_ratio(dimensions, output_dir)
    plot_gauge_errors(gauge_summary, output_dir)
    plot_phase_occupation_invariance(phase_dynamics, output_dir)

    phase_only_verified = bool(
        np.all(
            dimensions["phase_only_dimension"]
            == dimensions["expected_single_generator_dimension"]
        )
    )

    shift_only_verified = bool(
        np.all(
            dimensions["shift_only_dimension"]
            == dimensions["expected_single_generator_dimension"]
        )
    )

    pair_verified = bool(
        np.all(
            dimensions["phase_shift_dimension"]
            == dimensions["expected_pair_dimension"]
        )
    )

    print()
    print("Dynamic Closure Notebook — Entry 06")
    print("Why a Cyclic Dynamic Closure Requires Phase and Shift")
    print("-" * 64)
    print()
    print(
        "Phase-only algebra dimension equals k for all tested k: "
        f"{phase_only_verified}"
    )
    print(
        "Shift-only algebra dimension equals k for all tested k: "
        f"{shift_only_verified}"
    )
    print(
        "Phase + shift algebra dimension equals k^2 for all tested k: "
        f"{pair_verified}"
    )
    print()
    print(
        "Maximum Fourier duality error F^dagger Z F = X: "
        f"{fourier['Fdag_Z_F_minus_X_error'].max():.6e}"
    )
    print(
        "Maximum Fourier duality error F^dagger X F = Z^(-1): "
        f"{fourier['Fdag_X_F_minus_Zinv_error'].max():.6e}"
    )
    print()
    print(
        "Maximum closed-traversal gauge-to-shift error across all trials: "
        f"{gauge['gauge_to_shift_error'].max():.6e}"
    )
    print(
        "Maximum dressed Weyl-relation error across all trials: "
        f"{gauge['dressed_weyl_relation_error'].max():.6e}"
    )
    print()
    print(
        "Maximum occupation change under phase-only action: "
        f"{phase_dynamics['phase_only_occupation_change_L1'].max():.6e}"
    )
    print()
    print("Structural conclusion:")
    print(
        "    Phase distinguishability supplies Z; actual cyclic traversal "
        "supplies X up to gauge."
    )
    print(
        "    Either generator alone spans only a k-dimensional commutative "
        "algebra; together they span M_k(C), dimension k^2."
    )
    print()
    print(f"Outputs written to: {output_dir.resolve()}")


if __name__ == "__main__":
    main()
